# Generated by Django 5.2.16 on 2026-07-28 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=512)),
                ('pickup_location', models.CharField(max_length=512)),
                ('dropoff_location', models.CharField(max_length=512)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('total_distance_miles', models.FloatField()),
                ('total_driving_hours', models.FloatField()),
                ('total_duration_hours', models.FloatField()),
                ('num_days', models.PositiveIntegerField()),
                ('cycle_restart_required', models.BooleanField(default=False)),
                ('locations', models.JSONField(default=dict)),
                ('route_geometry', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='geocodecache',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reversegeocodecache',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='geocodecache',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='geocodecache',
            name='display_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='geocodecache',
            name='raw_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='geocodecache',
            name='state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='reversegeocodecache',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='reversegeocodecache',
            name='lat_key',
            field=models.DecimalField(db_index=True, decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='reversegeocodecache',
            name='lng_key',
            field=models.DecimalField(db_index=True, decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='reversegeocodecache',
            name='raw_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reversegeocodecache',
            name='remark',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='reversegeocodecache',
            name='state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('rest', 'Rest'), ('break', 'Break'), ('cycle_restart', 'Cycle Restart')], max_length=32)),
                ('sequence', models.PositiveIntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('remark', models.CharField(max_length=256)),
                ('duration_minutes', models.FloatField()),
                ('mile_marker', models.FloatField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DutyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=32)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('remark', models.CharField(max_length=256)),
                ('mile_marker', models.FloatField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_events', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('log_date', models.DateTimeField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_miles', models.FloatField(default=0)),
                ('segments', models.JSONField(default=list)),
                ('totals', models.JSONField(default=dict)),
                ('remarks', models.JSONField(default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
